import { AlertTriangle, CheckCircle2, Info, Sparkles, TriangleAlert } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardBody } from '@/components/ui/Card';
import { Spinner } from '@/components/ui/Spinner';
import { ErrorState } from '@/components/ui/ErrorState';
import { useInsights } from '../hooks';
import type { Insight } from '../api';

const severityConfig: Record<Insight['severity'], { icon: typeof Info; classes: string }> = {
  info: { icon: Info, classes: 'bg-blue-50 text-blue-600 border-blue-100 dark:bg-blue-500/10 dark:text-blue-400 dark:border-blue-500/20' },
  success: {
    icon: CheckCircle2,
    classes: 'bg-emerald-50 text-emerald-600 border-emerald-100 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20',
  },
  warning: {
    icon: TriangleAlert,
    classes: 'bg-amber-50 text-amber-600 border-amber-100 dark:bg-amber-500/10 dark:text-amber-400 dark:border-amber-500/20',
  },
  alert: { icon: AlertTriangle, classes: 'bg-red-50 text-red-600 border-red-100 dark:bg-red-500/10 dark:text-red-400 dark:border-red-500/20' },
};

export function AiInsightsPage() {
  const { data: insights, isLoading, isError, refetch } = useInsights();

  return (
    <div>
      <PageHeader
        title="AI Insights"
        description="Automatically generated signals from your customers, projects, tasks, and invoices."
      />

      {isLoading && <Spinner />}
      {isError && <ErrorState message="Failed to generate insights." onRetry={() => refetch()} />}

      {!isLoading && !isError && insights && (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {insights.map((insight) => {
            const { icon: Icon, classes } = severityConfig[insight.severity];
            return (
              <Card key={insight.id} className={`border ${classes}`}>
                <CardBody className="flex items-start gap-3">
                  <Icon className="mt-0.5 h-5 w-5 shrink-0" />
                  <div>
                    <p className="text-sm font-semibold text-slate-900 dark:text-slate-100">{insight.title}</p>
                    <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{insight.description}</p>
                  </div>
                </CardBody>
              </Card>
            );
          })}
        </div>
      )}

      <div className="mt-6 flex items-start gap-2 rounded-xl border border-dashed border-slate-300 p-4 text-xs text-slate-500 dark:border-slate-700 dark:text-slate-400">
        <Sparkles className="h-4 w-4 shrink-0" />
        <p>
          Insights are generated by a deterministic rules engine over your live data (overdue tasks, revenue trends,
          workload balance, top customers, overdue invoices). It's built as a swappable extension point for a real LLM
          integration later.
        </p>
      </div>
    </div>
  );
}
